# model parameters

model:
    - type: Sequential # type
    - in_nodes: 10 # input nodes
    - out_nodes: 10 # output nodes
    - layer_num: 5 # hidden layer
    - layer_nodes: [10, 3, 4, 5, 6] # hidden layer nodes

fit:
    - loss_func: adam # Loss function
